trigger:
  branches:
    include:
      - PlayWrightLearn

pool:
  vmImage: 'windows-latest'

steps:
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - task: PowerShell@2
    displayName: 'Install dependencies'
    inputs:
      targetType: 'inline'
      script: |
        npm ci

  - task: PowerShell@2
    displayName: 'Install Playwright Browsers'
    inputs:
      targetType: 'inline'
      script: |
        npx playwright install --with-deps

  - task: PowerShell@2
    displayName: 'Run Playwright Tests'
    inputs:
      targetType: 'inline'
      script: |
        npx playwright test --reporter=html

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Playwright HTML Report'
    inputs:
      targetPath: 'playwright-report'
      artifact: 'playwright-html-report'
      publishLocation: 'pipeline'
